### ISSUE TITLE
Velocity control feed forward gains

### ISSUE THREAD

**Issue by BryanStuurman** [xArm-Developer/xarm_ros#111]
For all the velocity trajectory controllers, the velocity_ff parameters are very low:
```
velocity_ff:
    joint1: 0.25
    joint2: 0.25
    joint3: 0.25
    joint4: 0.25
    joint5: 0.25
    joint6: 0.25
```

This is generally not how these controllers are set up; when one generates a trajectory the velocity portion is a perfect differentiation of the path, so in the ideal case the robot could move through the sequence of velocities and never deviate from the intended path. Here instead the feed forward term reduces the intended velocity by a factor of 4, and relies on the error correction part of the controller to make up the difference, leading to much higher than usual proportional gains and unworkable path tolerance per joint of 1 radian.

I'd like to see the velocity_ff terms raised to 1 and the error controller gains adjusted accordingly, and a path tolerance error of less than 0.1. I will be able to do some testing my one of my own 5 axis arms in about a week.
