### ISSUE TITLE
How to make sure that camera on base calibration is correct

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#132]
Hello, I am doing camera on base by setting <arg name="eye_on_hand" value="false" /> as false in calibration launch file. How can I make sure that the calibration I am doing is correct ? 

translation: 
  x: 0.4705739455942296
  y: 1.0399431884657737
  z: 0.6388135790952124
rotation: 
  x: -0.11958812174791901
  y: -0.7127805157974599
  z: 0.6887959517916398
  w: 0.056592881458372546

![image](https://user-images.githubusercontent.com/108360879/193107584-43e567b8-295c-40e9-bcaf-694ca8b7cc8e.png)

**Comment by penglongxiang** [comment]
I am afraid you have to do some measurement from the robot base to the camera lens, to know the rough relative coordinated distance from robot base (**/link_base**) to the RGB lens (**/camera_color_optical_frame**). Then to verify with the calibrated result. 

To verify the orientation result, I made a illustration of frame orientation on the realsense d435i, just for your reference.  

![企业微信截图_16652262735973](https://user-images.githubusercontent.com/6412261/194734306-16d4bee0-5255-4d9d-9f9a-9bf627595722.png)

image source: https://www.intelrealsense.com/depth-camera-d435i/

**Comment by Akumar201** [comment]
I would like to share the  tf to verify if I am doing it correctly, please verify 
[frames.pdf](https://github.com/xArm-Developer/xarm_ros/files/9758328/frames.pdf)

**Comment by penglongxiang** [comment]
hi, I am not expert on vision and calibration either, the only way I can think of is comparing with the known ground truth, and this verification needs to be done only once to confirm the reliability. Your calibration target in "eye-on-base" scenario is to calculate relative position and orientation between **robot base frame** (coordinate system) and the `/camera_color_optical frame` on the realsense camera. So just fix them at a known relative position like 2 meters away only in x direction then check the calibration result. The result given in output yaml has the units of meters and radians.

**Comment by Akumar201** [comment]
I have two follow up question just to make sure things are working perfectly, so I calibrated the camera with the following result 
parameters:
  ```
eye_on_hand: false
  freehand_robot_movement: false
  move_group: xarm6
  move_group_namespace: /
  namespace: /xarm_realsense_handeyecalibration_eye_on_base/
  robot_base_frame: link_base
  robot_effector_frame: link_eef
  tracking_base_frame: camera_color_optical_frame
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.053744796643656396
  qx: -0.06921099152218314
  qy: -0.7859133605577909
  qz: 0.6120960097754341
  x: 0.13260120526246572
  y: 1.4612716251100917
  z: 1.1730637467290128
```

Please let me know if I am thinking right 
  x: 0.13260120526246572 in meters is the distance from robot base frame (0,0,0) to /camera_color_optical frame in x direction
  y: 1.4612716251100917 in meters is the distance from robot base frame (0,0,0) to /camera_color_optical frame in y direction
  z: 1.1730637467290128 in meters is the distance from robot base frame (0,0,0) to /camera_color_optical frame in z direction
