### ISSUE TITLE
Unable to get data from the force toque sensor

### ISSUE THREAD

**Issue by nitish3693** [xArm-Developer/xarm_ros#148]
We are using the latest version of xarm_ros, and have connected the force sensor according to the manual. When running either the provided xarm6_server.launch, or the realMove_exec.launch, the two uf_ftsensor topics do become available, but there is no data published to them at all. We are not getting any error messages anywhere, and all other functionality works fine.

**Comment by MinnaZhong** [comment]
Hi, please update the firmware to the latest version V1.11.1.

**Comment by VFjr** [comment]
Hi, I am working together with @nitish3693 

We have updated the control box firmware to v1.11.1.

The force torque sensor works well when used with uFactory studio, including the manual mode. Here is a screenshot of our current setup:

![image](https://user-images.githubusercontent.com/56606852/201977655-8fc866fd-36a6-42b5-9da5-b48b353e10b7.png)

I ran the payload identification procedure. 

Then after closing the uFactory Studio, I tried running the following on the most recent version of the xarm_ros:

```
roslaunch xarm_bringup xarm6_server.launch robot_ip:=192.168.1.212 report_type:=rich
```

<details>
  <summary>Console Output</summary>

```
extend@extend-LattePanda-Delta:~/ws_force_sensor_test$ roslaunch xarm_bringup xarm6_server.launch robot_ip:=192.168.1.212 report_type:=rich
... logging to /home/extend/.ros/log/5483ac42-6503-11ed-bf65-00e04c018e53/roslaunch-extend-LattePanda-Delta-13266.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://extend-LattePanda-Delta:34803/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /xarm/DOF: 6
 * /xarm/add_gripper: False
 * /xarm/baud_checkset: True
 * /xarm/default_gripper_baud: 2000000
 * /xarm/enforce_limits: True
 * /xarm/joint_names: ['joint1', 'joint...
 * /xarm/uf_model: XARM
 * /xarm/velocity_control: False
 * /xarm/xarm_report_type: rich
 * /xarm/xarm_robot_ip: 192.168.1.212

NODES
  /xarm/
    uf_driver (xarm_api/xarm_driver_node)

auto-starting new master
process[master]: started with pid [13279]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5483ac42-6503-11ed-bf65-00e04c018e53
process[rosout-1]: started with pid [13293]
started core service [/rosout]
process[xarm/uf_driver-2]: started with pid [13296]
[ INFO] [1668530051.911351629]: namespace: /xarm
[ INFO] [1668530051.916012721]: xarm_driver_node start
SDK_VERSION: 1.11.0
Tcp control connection successful
FIRMWARE_VERSION: v1.11.1, PROTOCOL: V1, DETAIL: 6,6,XI1300,AC1300,v1.11.1
Tcp Report Rich connection successful
[ INFO] [1668530052.256383011]: [TCP STATUS] CONTROL: 1, REPORT: 1
report_data_size: 494, size_is_not_confirm: 0
change prot_flag to 3
```
  
</details>

The problem now is that it still does not to output the right data. On `uf_ft_sensor_raw_data`, it outputs some specific values constantly and the values do not change if applying a force to the sensor. On `uf_ft_sensor_ext_data`, it always outputs zeros. Both topics are published to with a frequency of about 5 Hz.

<details>
  <summary> Output of: rostopic echo /xarm/uf_ftsensor_raw_states                  </summary>
  
```
---
header: 
  seq: 118
  stamp: 
    secs: 1668530578
    nsecs: 569126847
  frame_id: "uf_ft_sensor_raw_data"
wrench: 
  force: 
    x: -15.6400003433
    y: 1.94000005722
    z: 22.3999996185
  torque: 
    x: -1.47399997711
    y: -0.638499975204
    z: 0.264499992132
---
header: 
  seq: 119
  stamp: 
    secs: 1668530578
    nsecs: 769775898
  frame_id: "uf_ft_sensor_raw_data"
wrench: 
  force: 
    x: -15.6400003433
    y: 1.94000005722
    z: 22.3999996185
  torque: 
    x: -1.47399997711
    y: -0.638499975204
    z: 0.264499992132
---
header: 
  seq: 120
  stamp: 
    secs: 1668530578
    nsecs: 969882188
  frame_id: "uf_ft_sensor_raw_data"
wrench: 
  force: 
    x: -15.6400003433
    y: 1.94000005722
    z: 22.3999996185
  torque: 
    x: -1.47399997711
    y: -0.638499975204
    z: 0.264499992132
---

```
  
</details>

<details>
  <summary> Output of: rostopic echo /xarm/uf_ftsensor_ext_states </summary>

```
---
header: 
  seq: 806
  stamp: 
    secs: 1668530213
    nsecs: 518952255
  frame_id: "uf_ft_sensor_ext_data"
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
---
header: 
  seq: 807
  stamp: 
    secs: 1668530213
    nsecs: 719285943
  frame_id: "uf_ft_sensor_ext_data"
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
---
header: 
  seq: 808
  stamp: 
    secs: 1668530213
    nsecs: 919248522
  frame_id: "uf_ft_sensor_ext_data"
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0
---
```
  
</details>
