### ISSUE TITLE
XArm shaking while moving when used with moveit servoing

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#164]
Hi, I am using XArm with moveit servoing. The arm is not moving smooth it's taking jerks while moving. I tried changing the following parameters as suggested in https://github.com/xArm-Developer/xarm_ros2/issues/2 and https://github.com/xArm-Developer/xarm_ros2/issues/24 . 

#### XArm_config.yaml

```
publish_period: 0.1  # 1/Nominal publish rate [seconds]
low_latency_mode: true  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

```
Changed publish rate in these two controllers file 

#### XArm6_position_controllers.yaml

```
# xarm:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
```
#### XArm6_traj_controller.yaml

```

# xarm:
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
  
```
launching ` realMove_exec.launch` with `report_type:=dev` I am not using velocity as true. Please suggest me where I might be missing 
as doing 
`rostopic hz /xarm/xarm6_traj_controller/command
`

shows 
```

subscribed to [/xarm/xarm6_traj_controller/command]
average rate: 9.999
	min: 0.100s max: 0.100s std dev: 0.00011s window: 10
average rate: 10.000
	min: 0.100s max: 0.100s std dev: 0.00011s window: 20
average rate: 9.999
	min: 0.100s max: 0.100s std dev: 0.00009s window: 30
average rate: 10.285
	min: 0.001s max: 0.100s std dev: 0.01624s window: 37

```
which is pretty slow.
