### ISSUE TITLE
Publish period or update_rate for moveit servoing xarm6_traj_controller

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#173]
Hi, I am playing around with the xarm_servoing example. I have noticed that in the [`realMove_exec.launch`](https://github.com/xArm-Developer/xarm_ros/blob/master/xarm6_moveit_config/launch/realMove_exec.launch) we are using [`xarm6_traj_controller`](https://github.com/xArm-Developer/xarm_ros/blob/master/xarm_controller/config/xarm6_traj_controller.yaml)

**realMove_exec.launch**
```
 <!-- load the joint trajectory controller specified in yaml -->
  <rosparam file="$(find xarm_controller)/config/xarm6_traj_controller.yaml" command="load" ns="$(arg xarm_hw_ns)"/>
  <arg name="xarm_traj_controller" value="$(eval 'xarm6_traj_controller_velocity' if arg('velocity_control') else 'xarm6_traj_controller')" />
  <node
    name="traj_controller_spawner"
    pkg="controller_manager"
    type="spawner"
    respawn="false"
    output="screen"
    ns="$(arg xarm_hw_ns)"
    args="$(arg xarm_traj_controller)"/>
```
**xarm6_traj_controller.yaml**

  
```
xarm6_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.05
      joint1: {trajectory: 1, goal: 0.01}
      joint2: {trajectory: 1, goal: 0.01}
      joint3: {trajectory: 1, goal: 0.01}
      joint4: {trajectory: 1, goal: 0.01}
      joint5: {trajectory: 1, goal: 0.01}
      joint6: {trajectory: 1, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10
```
As suggested in this github response https://github.com/xArm-Developer/xarm_ros2/issues/24 , 
`
Modify xarm_controller/config/xarm6_controllers.yaml (note that the 6-axis is used as an example), and appropriately increase the update_rate (100?)`
But as I am working in ROS one I have `xarm_controller/config/xarm6_traj_controller.yaml` the controller does not have a update_rate (100?) .
Which controller would be best to use with moveit servoing as now I can see we are using `xarm6_traj_controller`
 So what should I do , any help would be much appreciated.
