### ISSUE TITLE
Max velocity limit for Xarm6 in joint_limits.yaml

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xarm_ros#175]
Hi, I am trying to achieve maximum velocity. I would like to know what would be the max velocity I should use in the following file, is there any safety issue I need to take care of while increasing the speed. Is `max_velocity: 2.14` in m/sec or radian/sec

```
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: false
    max_acceleration: 0
  joint2:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: false
    max_acceleration: 0
  joint3:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: false
    max_acceleration: 0
  joint4:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: false
    max_acceleration: 0
  joint5:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: false
    max_acceleration: 0
  joint6:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: false
    max_acceleration: 0
```
