### ISSUE TITLE
Joint states frequency

### ISSUE THREAD

**Issue by JuliusSustarevas** [xArm-Developer/xarm_ros#96]
Hi I believe this question was asked before but I just want to check if there are any updates. The joint state feedback coming from xarm is still 10Hz max? Is there any way to make it faster or any plans to make it faster ?

**Comment by penglongxiang** [comment]
Hi, now you can add `report_type:=dev` at launching the real-arm applications, to boost the feedback rate to 100Hz. Please note the joint velocity may not be very accurate with 100Hz report, we will try to optimize this later.

**Comment by JuliusSustarevas** [comment]
Whats the nature of inaccuracy? Just small over/under reporting? Or
something more significant? No large spikes i hope? and no latency?

**Comment by JuliusSustarevas** [comment]
Hi So I just want to understand whats happening here: 
![image](https://user-images.githubusercontent.com/33488780/150521140-352d9a52-4236-42b5-bc72-665498e59cf5.png)

I just updated to the current git commit. I am recording joint states just coming from the service-based hw-interface read function. And joint command I'm sending via velocity controller.  In the plot - red line is the velocity command on joint 1.  Blue line is velocity joint_state of joint 1. 

My questions is: 
- Why is there a 0.2 rad steady state overshoot on the joint velocity?  So I command 0.1rad/s and it goes at 0.12. 
- Why there are 0,4 rad dips in the joint state velocity?  you cans ee blue signal drop from 0.12 to 0.8. 
- Why is there noise on the steady signal? I assume that's the inaccuracy you have from encoders? its about 0.02rad  amplitude wave
-  i can see a PID overshoot and that's fine its just weird why its going for 0.12

**Comment by JuliusSustarevas** [comment]
![image](https://user-images.githubusercontent.com/33488780/150523629-a290cbd3-4c47-4beb-9a43-5ee2a6e64fd5.png)
The under/overshoots aare quite severe on velocity. Also not sure why they are growing. I suspect you put your gains too high in order to overcome initial friction at low velocities?

**Comment by penglongxiang** [comment]
Hi @JuliusSustarevas , to answer all these questions, we need more information for reproducing these outputs.
1. what is the version of your controller firmware?
2. what was the full xarm_ros launching command you use, was it specified with `report_type:=dev`? 
3. what was the source of data marked blue (joint1 feedback velocity)? Was it from `velocity` field of topic `/joint_states`? 
4. what was the frequency you gave for command marked red (joint 1 velocity command)? Since there is no unit remark of the horizontal/vertical axis on the diagram. 
5. Is it possible to send us the log package downloadable from xArm Studio?

**Comment by penglongxiang** [comment]
> 

Currently the `/joint_states` velocity information is just digital differentiation from the position report. Which may have spikes and oscillations especially at high frequency. We are trying to find a better way to get more accurate velocity feedback, like filtering, or use the controller reported joint velocity (but only available at 5Hz now).

**Comment by JuliusSustarevas** [comment]
> 

1. xarm is on firmware  1.7.1  and github commit hash: 9d59340503a48afbc2e3ea8095b9828d2d955a5a
2. This experiment was done with report type normal.  I load up the driver and a combined hardware interface (other parts of the robot).  The driver is loaded as follows:
```  <group if="$(arg xarm_on)" ns="xarm">
            <param name="xarm_robot_ip" type="str" value=" <ip>" />
            <param name="velocity_control" value="<true>" />
            <param name="xarm_report_type" type="str" value="<normal>" />
            <rosparam file="$(find as_control)/config/joint_limits.yaml" command="load" />
            <node name="xarm_driver" pkg="xarm_api" type="xarm_driver_node" output="screen" />
        </group>```
        
A combined hardware interface is loaded up too. The controllers acting on xarm are velocity controller and joint state controller
``` 
xarm_joint_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints: 
      - xarmjoint1
      - xarmjoint2
      - xarmjoint3
      - xarmjoint4
      - xarmjoint5
      - xarmjoint6
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
    ```
    3. Im adding a picture to explain better. xarm_driver is the xarm_driver. armstone_driver is the combined hw interface that does the read. The experiment in previous post blue line is the msg.velocity[0] of sensor_msgs/JointStates msg from "/as_control/joint_states" topic (which is generated by the joint_state_controller loaded by hardware interface). I can see hw_interface still subscribes to xarm_states but the data is coming from the read().
    
![image](https://user-images.githubusercontent.com/33488780/150766144-b3463340-9afd-4799-95da-1ea7cc2350bf.png)

    4. horizontal axis is seconds from start ye. 
    5. yes

**Comment by penglongxiang** [comment]
Hi @JuliusSustarevas , thanks for the detailed information. From the log I actually saw received velocity commands are constantly varying at 50Hz, however from your diagrams the commands are updated far less often. I have not used `velocity_controllers/JointGroupVelocityController` before, but it's supposed to be just a forward-command-controller and no pid control loop needed.

We may need more time to identify the cause, since we do not have the exact code, it would be more helpful if you could check the command sent to robot through write().  Also, your velocity feedback seems to change at more than 5Hz under `normal` report, please help to confirm.

Another question is: was your application cpu heavy or IO consuming? We are not quite sure if the velocity can calculate well if network is heavy or system delay occurs now and then.

**Comment by penglongxiang** [comment]
Hi @JuliusSustarevas , here are some updates about our reproduction of the issue. 

1. Controller firmware version: v1.7.1, and xarm_ros is the latest commit.
2. load the single joint velocity controller as: (just test for joint 1)
```
joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint1
```
3. controller manager updates at 100Hz as we currently do.
4. send velocity command using command line like:
```
rostopic pub -1 /xarm/joint1_velocity_controller/command std_msgs/Float64  0.1
```
5. observe the joint velocity calculated at driver_node at: 
https://github.com/xArm-Developer/xarm_ros/blob/9d59340503a48afbc2e3ea8095b9828d2d955a5a/xarm_api/src/xarm_driver_node.cpp#L63
Which is supposed to be published to `/joint_states` velocity field.

6. Here is the plot of joint velocity observation from step 5, the velocity command sent are(rad/s): 0.05, 0.2, -0.15, -0.12, 0.1, 0.0. The time unit of horizontal axis is also 'seconds'. 

![Screenshot from 2022-01-26 18-08-04](https://user-images.githubusercontent.com/6412261/151146870-b4de6727-ee23-47b0-a743-6f11b4339143.png)

As can be seen the overshoot and oscillations are not as severe as from your side. Moreover, the velocity controller behaves as expected, the command sent to xArm is at 100Hz, but value will not change as long as no new command sent by command line in step 4.

It says the `velocity_controllers/JointGroupVelocityController` is just a group version of `velocity_controllers/JointVelocityController` used in this test and they should behave the same. I will continue to test on JointGroupVelocityController later.

**Comment by JuliusSustarevas** [comment]
Hi thanks so much for this. My setup was pretty much identical. 

To answer previous questions:
- My setup is this https://github.com/JuliusSustarevas/ArmStone  (see as_control) but ofc its for a specific robot. But you can see what I'm calling. should be normal dev type. 
- Yes it seems with normal report type I'me getting 50hz . i presume because from current commit its actually called the service from the driver so this is expected. 

#Clarifications:
- Did i understand correctly that from data from the arm you see that the **velocity command** was oscillating? 
- From your previous post the velocity command is actually generated in the write() ... but seems the write is actually calling something in the driver? and that just sets a new joint position by integrating velocity?


I'll try to dive again in write/read and interactions with the driver. I'm beginning to think that I should not use the hw_interface  as it just wraps the drive. the services for joint state feedback and velocity commands are probably exposed directly right? I can just call those directly. 


Given that on your side it is not reproducable - this suggests that its the hardware interface messing up its cycles?  If you try with all joint controller - that would mean calling 6 services instead of 1  every cycle. maybe that will cause more deterioration?  In my case I have extra 4 motors being cycled through.

**Comment by penglongxiang** [comment]
Hi @JuliusSustarevas , for your clarifications:
1. Yes, as the controller log indicates: velocity command was sent in 100Hz, but the value changes (oscillates) at 50Hz. I will post a small part from the log for your reference: [log_part.txt](https://github.com/xArm-Developer/xarm_ros/files/7947455/log_part.txt) 
2. The command is not generated in the write(), but in the update() method in ros-controller loaded by controller_manager, in your case, should be `velocity_controllers/JointGroupVelocityController` . I kind of suspect the controller actually running is not a forward-command-controller, **but some other one using PID feedback control**. Since feedback from `joint_state_publisher` is supposed to operate at 50Hz. Please help checking the loaded controller by:
```
 rosservice call /[your namespace]/controller_manager/list_controllers  
```
my output is like this:
```
controller: 
  - 
    name: "joint_state_controller"
    state: "running"
    type: "joint_state_controller/JointStateController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::JointStateInterface"
        resources: []
  - 
    name: "joint_velocity_controller"
    state: "running"
    type: "velocity_controllers/JointGroupVelocityController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::VelocityJointInterface"
        resources: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]

```
3. In the meantime, I tried the JointGroupVelocityController and control 7 joints together, the feedback still behaves normally (calculated in 5Hz under normal report), similar to my previously posted diagram. I am not sure if the oscillation of the feedback velocity is related to the oscillating command on your side. The only thing I do not understand now is why your velocity from `/joint_states` can vary at more than 5Hz, I will dig more into it.

**Comment by penglongxiang** [comment]
I just noticed `JointStateController` will also publish to `joint_states` topic if it is running, in the frequency specified in its config (`50Hz` here). And the velocity it publishes is indeed oscillating, this may be the actual data source of you blue line. A way to identify the state published by our driver from the same topic is: the `frame_id` is "***joint-state data***" rather than empty.

I captured some frames of the `JointStateController` published data:
```
---
header: 
  seq: 2303
  stamp: 
    secs: 1643269768
    nsecs: 316697469
  frame_id: ''
name: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]
position: [-0.9359999895095825, -6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.46799999475479126]
velocity: [-0.11922166652689098, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05961083326344549]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 2304
  stamp: 
    secs: 1643269768
    nsecs: 327934714
  frame_id: ''
name: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]
position: [-0.9372000098228455, -6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.46860000491142273]
velocity: [-0.11801686956336851, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05900843478168426]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 2305
  stamp: 
    secs: 1643269768
    nsecs: 357517282
  frame_id: ''
name: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]
position: [-0.9399999976158142, -6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.4699999988079071]
velocity: [-0.07913817827940021, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03956908913970011]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 2306
  stamp: 
    secs: 1643269768
    nsecs: 368871543
  frame_id: ''
name: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]
position: [-0.9412000179290771, -6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.4706000089645386]
velocity: [-0.11851995118867469, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05925997559433734]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 2307
  stamp: 
    secs: 1643269768
    nsecs: 388624605
  frame_id: ''
name: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]
position: [-0.9431999921798706, -6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.4715999960899353]
velocity: [-0.11868889302058212, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05934444651029106]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 2308
  stamp: 
    secs: 1643269768
    nsecs: 408326389
  frame_id: ''
name: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]
position: [-0.9452000260353088, -6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.4726000130176544]
velocity: [-0.11823474117946216, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05911737058973108]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
The velocity command given here is  [-0.1, 0, 0, 0, 0, 0, 0.05]. I observed from its timestamp that the actual rate is not that stable, and I am not aware how the velocity is calculated since only joint position is updated now in xArmHW::read(), calculation with two adjacent position and the time-stamp difference does not match with its velocity value, research on the 'ros_control' source code is needed for its algorithm. 

For speed monitoring, I suggest you can **try removing the spawning of JointStateController** and simply use the state published from our driver. Check if the monitored velocity can be better this way. The joint state published by xarm_driver in my same experiment is:
```
header: 
  seq: 244
  stamp: 
    secs: 1643269768
    nsecs: 423874944
  frame_id: "joint-state data"
name: [joint1, joint2, joint3, joint4, joint5, joint6, joint7]
position: [-0.9467999935150146, -6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.4733999967575073]
velocity: [-0.10008712856336875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.050043564281684376]
effort: [0.012418649159371853, -6.752345561981201, 0.037371568381786346, 3.9327456951141357, -0.007377090863883495, -0.8894346952438354, 0.07369352877140045]
```

Another thing is: in the controller log on system date 2022-01-21, I did not see the xarm.getServoAngle() which is called in xArmHW::read() in current commit: 9d59340503a48afbc2e3ea8095b9828d2d955a5a, if not called it should be the old implementation of xArmHW::read() which had no active acquisition of joint angles but using reported data as controller feedback. Maybe you have not updated to the latest xarm_ros back then?
